<a href="https://colab.research.google.com/github/HarishBankai/SY-FDS/blob/main/Lab_1_FDS_18001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#declare array using np.array
A = np.array([[4, 6],
              [6, 9]])

B = np.array([[3, 4] ,
             [7, 9]])

print("First Matrix : \n", A)  #print the array
print("Second Matrix : \n", B)

rank = np.linalg.matrix_rank(A)  #use rank syntax for formula

determinant = np.linalg.det(A)

transpose = A.T

if(np.linalg.det(A) != 0):
  inverse = np.linalg.inv(A)
  print("\nInverse is \n", inverse)
else:
  print("\nInverse does not exist \n")

eigenvalues, eigenvectors = np.linalg.eig(A)

result = np.dot(A, B)

print("Rank is \n", rank)
print("\nDeterminant is \n", determinant)
print("\nTranspose is \n", transpose)
print("\nEigenvalues are \n", eigenvalues)
print("\nEigenvectors are \n", eigenvectors)

print("Result of Multiplication Matrix : \n", result)


First Matrix : 
 [[4 6]
 [6 9]]
Second Matrix : 
 [[3 4]
 [7 9]]

Inverse does not exist 

Rank is 
 1

Determinant is 
 0.0

Transpose is 
 [[4 6]
 [6 9]]

Eigenvalues are 
 [ 0. 13.]

Eigenvectors are 
 [[-0.83205029 -0.5547002 ]
 [ 0.5547002  -0.83205029]]
Result of Multiplication Matrix : 
 [[ 54  70]
 [ 81 105]]


In [ ]:
import numpy as np

A = np.array([5, 6, 8, 3, 74, 25])

print("Array : \n", A)

min_value = np.min(A)
max_value = np.max(A)

print("Minimum Element : ", min_value)
print("Maximum Element  : ", max_value)

Array : 
 [ 5  6  8  3 74 25]
Minimum Element :  3
Maximum Element  :  74


In [ ]:
import numpy as np

A = np.array([5, 6, 8, 3, 74, 25])

print("Array : \n", A)

sortedarray = np.sort(A)

print("Sorted Array : ", sortedarray)

Array : 
 [ 5  6  8  3 74 25]
Sorted Array :  [ 3  5  6  8 25 74]


In [ ]:
import numpy as np
A = np.array([5, 6, 8, 3, 74, 25])
print("Array : \n", A)
mean = np.mean(A)
print("Array : ", mean)

Array : 
 [ 5  6  8  3 74 25]
Array :  20.166666666666668
